### ISSUE TITLE
Feature/frontend pages #7：otree 的前端顯示有問題

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_django_backend#8]
目前的前端，使用 npm start 可以正確看到 Route 後的 Menu。

但是用 npm build 後，使用 otree deserver 開啟後端跟前端畫面，看不到 build 後的畫面。

**Comment by moneychien19** [comment]
這樣應該是正常的，前端拆出來 React 就是完全廢棄 django (otree) 的 view 的部分，所以要起一個完整的服務就是要在兩個 terminal 分別起前後端，然後我們目前專案裡有寫死一些路徑，像是前端就是 `localhost:3000`，後端是 `localhost:8000`，中間用 api 連在一起這樣

deploy 的時候想像也會是這樣，就是兩條路，他們會擁有不同的 domain
- 用 heroku deploy django，這部分應該就是跟原本一樣，你應該有經驗
- 另外 deploy React，這部分可以用其他的服務，或是 heroku 也可以，如果要免費可以用 Netlify
